# Generated by Django 2.0.1 on 2018-02-17 16:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(default=None)),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=datetime.datetime(2018, 2, 17, 17, 55, 26, 932995))),
                ('stop', models.DateTimeField(default=None)),
                ('time', models.IntegerField(default=None)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetracking.Project')),
            ],
        ),
    ]
