# Generated by Django 2.0.1 on 2018-03-11 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0003_auto_20180311_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 11, 14, 53, 12, 599951)),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 11, 14, 53, 12, 600453)),
        ),
    ]
