# Generated by Django 2.0.1 on 2018-03-11 14:11

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetracking', '0004_auto_20180311_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 11, 15, 11, 47, 394733)),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 11, 15, 11, 47, 395235)),
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='project',
        ),
        migrations.AddField(
            model_name='userproject',
            name='project',
            field=models.ManyToManyField(to='timetracking.Project'),
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='user',
        ),
        migrations.AddField(
            model_name='userproject',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
