# Generated by Django 2.0.1 on 2018-03-11 14:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetracking', '0005_auto_20180311_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 11, 15, 21, 11, 21376)),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 11, 15, 21, 11, 21877)),
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='project',
        ),
        migrations.AddField(
            model_name='userproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetracking.Project'),
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='user',
        ),
        migrations.AddField(
            model_name='userproject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
