# Generated by Django 2.0.1 on 2018-03-11 14:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0006_auto_20180311_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 11, 15, 24, 14, 548148)),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 11, 15, 24, 14, 548651)),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timetracking.Project'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
